### ISSUE TITLE
504 Gateway time-out error on plugins.php

### ISSUE THREAD

**Issue by ChrisTec-Dev** [joomlaworks/wp-memcached-object-cache#1]
Hello, after upload object-cache.php on /wp-content/, memcached function well on the wordpress back office, but I have a problem with my plugins management page. When I try to open the page, it generates a 504 Gateway time-out error. How to solve this problem.

**Comment by fevangelou** [comment]
Didn't have notifications on for this project, so I missed your comment... This cache driver should not affect the backend, in other words, the 504 relates to overall lag in your server.

**Comment by fevangelou** [comment]
(added correction)
