### ISSUE TITLE
Undefined offset: 1  wp-content/object-cache.php:516

### ISSUE THREAD

**Issue by JiveDig** [joomlaworks/wp-memcached-object-cache#2]
Refers to:
```
@list($node, $port) = explode(':', $server);
```

We see this quite often though caching still appears to be working correctly. Could this be a configuration thing, or this code needing a reindex or conditional in that loop?

**Comment by JiveDig** [comment]
Btw, thanks for maintaining this, it's quite useful as you already know :)

The issue is when using the default `'127.0.0.1'` and not declaring `get_memcached_servers()` in wp-config.php. I'm not a server expert, but is it safe to use the default of `'127.0.0.1:11211'` instead? It seems to break because explode doesn't find any `:`.

If I add this to wp-config it works:
```
function get_memcached_servers() {
	return [
		'127.0.0.1:11211',
	];
}
```

But I'm wondering if that's necessary, shouldn't the defaults do this?

**Comment by fevangelou** [comment]
Issued an update (v1.1) addressing this more elegantly :)

Thanks for the feedback.

**Comment by JiveDig** [comment]
That'll do it, thanks :)

Tested and confirmed it works without needing `get_memcached_servers()` in our config anymore.
